
server:
  error:
    include-message: always
    include-binding-errors: always

    spring:
      datasource:
        password:
          url: jdbc:mysql://localhost:8080/registration
          username:
            jpa:
              hibernate:
                ddl-auto: create-drop
              properties:
                hibernate:
                  dialect: org.hibernate.dialect.H2Dialect
                  format_sql: true
                  show-sql: true